const descriptionsData = {
    "x": {
        "3": "Cada entrega es un caso único que exige soluciones a medida. Su valor reside en la inspiración del momento, pero esto genera una carga cognitiva agotadora. Aquí, una IA debe ser solo un espejo para rebotar ideas, pues intentar automatizar sería una fricción inútil. El Sistema Operativo Interno debe ser apenas una bitácora ligera que capture criterios para que el conocimiento no se evapore.",
        "4": "Variedad casi absoluta, aunque ocasionalmente aparecen destellos de recurrencia que le recuerdan a algo ya vivido. El trabajo depende de personas clave y su intuición. En este nivel, la IA es un chatbot para organizar información dispersa, intentar automatizar sería una fricción inútil. Su Sistema Operativo Interno debe empezar a identificar módulos, plantillas o activos, para construir un primer inventario de recursos básicos.",
        "5": "Frontera donde la rutina y la creatividad chocan a diario. La mitad de las tareas ya tienen un rostro conocido. Hay una sensación de predictibilidad a medias. La IA aquí ayuda solamente en lo rutinario para liberar el alma del equipo. Su Sistema Operativo Interno debe separar formalmente lo variable de lo repetible para que el equipo deje de reconstruir pasos innecesariamente.",
        "6": "La operación tiene entradas y salidas visibles, pero los puentes entre ellas son frágiles. Hay proyectos que siguen un molde y otros completamente nuevos. La IA ayuda a clasificar datos y generar reportes, pero solo si el brief de entrada es claro. Su Sistema Operativo Interno debe formalizar los flujos cíclicos y definir responsables para que las lógicas no se confundan.",
        "7": "Navega por aguas semi-predecibles. Gran parte del esfuerzo puede anticiparse antes de empezar. La repetición es funcional, aunque surjan excepciones que exigen atención. Es el momento de usar IA genérica (APIs centralizadas) para crear piezas intermedias. Su Sistema Operativo Interno debe orquestar los flujos para que la tecnología ejecute mientras su equipo supervisa los casos atípicos.",
        "8": "La operación tiene una estructura reconocible, pero la ejecución varía según el caso. Los procesos existen, pero no siempre se aplican con rigor. La IA puede ayudar a estandarizar tareas repetitivas y generar reportes automáticos, pero las decisiones estratégicas siguen dependiendo del equipo. Su Sistema Operativo Interno debe formalizar los flujos principales y crear guías de referencia para que el equipo pueda operar con mayor autonomía.",
        "9": "La operación fluye con ritmo, aunque cada proyecto exige adaptaciones. Hay procesos claros, pero la flexibilidad es clave para responder a los clientes. La IA puede automatizar tareas repetitivas y generar borradores, pero el equipo mantiene el control creativo. Su Sistema Operativo Interno debe documentar los flujos existentes y crear plantillas reutilizables para agilizar el trabajo.",
        "10": "La operación tiene una base sólida y predecible. La mayoría de las tareas siguen patrones claros y repetitivos, aunque ocasionalmente surjan imprevistos. La IA puede automatizar gran parte del trabajo, liberando al equipo para enfocarse en tareas de mayor valor. Su Sistema Operativo Interno debe optimizar los flujos existentes y crear sistemas de monitoreo para asegurar la calidad y eficiencia.",
        "11": "La operación es altamente predecible y eficiente. Los procesos están bien definidos y se aplican de manera consistente, lo que permite una ejecución rápida y de alta calidad. La IA puede automatizar la mayoría de las tareas, como un componente estructural autónomo, la automatización es estratégica. liberando al equipo para enfocarse en la innovación y la mejora continua. Su Sistema Operativo Interno debe centrarse en la optimización continua y la automatización avanzada para mantener la ventaja competitiva.",
        "12": "La operación es altamente predecible y eficiente. Los procesos están bien definidos y se aplican de manera consistente, lo que permite una ejecución rápida y de alta calidad. La IA puede automatizar la mayoría de las tareas, liberando al equipo para enfocarse en la innovación y la mejora continua. Su Sistema Operativo Interno se auto-regula, permitiendo que el equipo se enfoque en la innovación y la mejora continua."
    },
    "y": {
        "3": "Sus decisiones nacen del caso a caso, sin referencias estables, todo es situacional. El -por qué- se hace algo es un conocimiento tácito que no se comunica. La IA puede asistir en tareas colaterales, pero no sustituye su juicio. Su Sistema Operativo Interno debe ser un Cerebro Externo, donde registre decisiones para empezar a ver patrones de pensamiento.",
        "4": "El conocimiento vive en las cabezas de los más experimentados y el equipo aprende por cercanía, como un relato heredado. Si esas personas faltan, el criterio desaparece con ellas. La IA es un apoyo individual, sin consistencia colectiva. Su Sistema Operativo Interno debe extraer esas reglas implícitas mediante sesiones de análisis para que el saber empiece a circular.",
        "5": "Existen acuerdos verbales y hábitos compartidos, una forma implícita de hacer las cosas que todos reconocen pero nadie ha escrito. La IA apoya tareas individuales con resultados inconsistentes entre personas. Su Sistema Operativo Interno debe redactar las -Reglas de Oro- innegociables para crear una primera base de estructura compartida.",
        "6": "Cuenta con manuales básicos, pero a menudo se omiten porque no reflejan la realidad diaria. La IA empieza a ser útil donde el criterio ya está articulado. Su Sistema Operativo Interno debe convertir esas guías en checklists obligatorias para asegurar que el criterio mínimo se cumpla siempre, sin excepciones caprichosas.",
        "7": "Existen caminos trazados para las dudas frecuentes, reduciendo las consultas a los líderes, el criterio actúa dentro de un marco claro. La IA puede integrarse en flujos de apoyo mediante APIs. Su Sistema Operativo Interno debe crear -Árboles de Decisión- para que los perfiles junior resuelvan problemas de forma autónoma.",
        "8": "El trabajo circula con la confianza de que el criterio se mantendrá estable sin importar quién lo ejecute. El sistema ya resolvió las preguntas fundamentales de calidad. La IA actúa como ejecución guiada individualmente. Su Sistema Operativo Interno debe auditar cuellos de botella donde la decisión todavía requiera una firma humana innecesaria.",
        "9": "La estandarización es parte de su cultura y las decisiones habituales no requieren consulta porque la referencia es sólida. La IA puede tomar decisiones colaterales dentro de parámetros definidos. Su Sistema Operativo Interno debe consolidar estas reglas y permitir -zonas de experimentación- para que la norma no bloquee la innovación.",
        "10": "Las decisiones operativas están externalizadas, la incorporación de nuevas personas es fluida porque el conocimiento no depende de quién lo transmite. La IA en arquitectura distribuida tiene aquí un entorno fértil. Su Sistema Operativo Interno debe asegurar que se capture el razonamiento detrás de las decisiones y no solo los pasos mecánicos.",
        "11": "Las reglas del sistema dictan el curso de acción, su equipo es gestor de una arquitectura con vida. La IA, mediante modelos locales y APIs entrenados con sus propios documentos, puede actuar como un consultor 24/7. Su Sistema Operativo Interno permite delegar criterio a cualquier integrante con una comprensión básica del sistema.",
        "12": "La ambigüedad ha desaparecido, el sistema es un lenguaje claro que se auto-regula y entrena a los demás. La IA distribuida puede ser parte de su arquitectura de decisión autónoma. Su Sistema Operativo Interno debe ser un organismo que aprende y se refina, devolviéndole a usted la soberanía técnica completa para transformar su empresa a su propio ritmo."
    }
};